name: Flutter CI/CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.3'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web
              
      - name: Fix index.html
        run: |
            sed -i 's/href="href=".\//href="/g' build/web/index.html
            
      - name: Zip Web
        run: 7z a -tzip web.zip build/web/
            
      - name: Upload Web
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: web.zip
      
  create-release:
    name: Create Release
    needs: [build-web]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
        
  upload-assets:
    needs: [create-release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [web]
    steps:
      - name: Download Assets
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.os }}
            
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./${{ matrix.os }}
          asset_name: ${{ matrix.os }}
          asset_content_type: application/octet-stream